spring:
  datasource:
    url: jdbc:mysql://172.16.1.101:3306/spring?autoReconnect=true&useUnicode=true&characterEncoding=utf8
    username: root
    password: Jkdz8888
    driver-class-name: com.mysql.jdbc.Driver